### ISSUE TITLE
where is sql file?

### ISSUE THREAD

**Issue by elviskudo** [clevertech/YiiBackbone#10]
thanks sir,

i really appreciate about your work, its really awesome to combine backbone with yii.
i install it to my localhost
but i see error about sql problem like this:

CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.yii_session' doesn't exist. The SQL statement executed was: 
SELECT data FROM yii_session
WHERE expire>1352778144 AND id=:id
. Bound with :id='a71fb8919ae9a9305e5f609c716bf701'

what i have supposed to do, thanks again for the system

**Comment by tonydspaniard** [comment]
It seems that you have configured your session to be saved to the database. 

Make sure you configure it properly that automatically creates the table if doesn't exists (check Yii library)

Cheers and thanks!
Enviado desde mi BlackBerry® de Vodafone

-----Original Message-----

**Comment by elviskudo** [comment]
thanks tony
i got the migrations folder then i ran it, so here it is, it's just works
