### ISSUE TITLE
Wrong username and password!!

### ISSUE THREAD

**Issue by cherifGsoul** [clevertech/YiiBackbone#7]
Can you update the readme file for the correct username and password please, for now I looked to migration file and I got the password.

**Comment by rinatio** [comment]
Thank you, corrected.

**Comment by leo4all** [comment]
This username / password not working even on demo site.

**Comment by rinatio** [comment]
@leo4all it was working fine until someone logged in and deleted all users. I updated readme with another user credentials and fixed `UserController::accessRules()`. Your local setup still should be working with super/1q2w3e credentials.

**Comment by leo4all** [comment]
thanks mate.
